'use client'

import { useMemo, useState } from 'react'
import {
  Archive, ArrowUpRight, BarChart3, Bell, CalendarDays, Check, ChevronDown,
  CircleHelp, Clapperboard, FileText, Film, FolderKanban, Grid2X2, Inbox,
  Lightbulb, ListFilter, Menu, MoreHorizontal, Palette, Plus, Search, Settings2,
  Sparkles, Sun, Moon, Users, WandSparkles, X, Video,
} from 'lucide-react'

const columns = [
  { id: 'idea_pending', label: 'Ý tưởng mới', color: 'bg-amber-400', count: 4 },
  { id: 'scripting', label: 'Đang viết kịch bản', color: 'bg-blue-400', count: 3 },
  { id: 'shooting_pending', label: 'Chờ quay', color: 'bg-violet-400', count: 2 },
  { id: 'shooting_done', label: 'Đã quay', color: 'bg-cyan-400', count: 2 },
  { id: 'editing_done', label: 'Chờ duyệt video', color: 'bg-orange-400', count: 2 },
  { id: 'published', label: 'Đã đăng', color: 'bg-emerald-400', count: 5 },
]

const initialCards = [
  { id: 1, title: '3 cách phối đồ linen cho ngày hè', type: 'Tổng hợp outfit', owner: 'Minh Anh', initials: 'MA', status: 'idea_pending', platforms: ['TikTok', 'Instagram'], due: 'Hôm nay', priority: 'Ưu tiên' },
  { id: 2, title: 'Fitcheck: Essential Polo 2025', type: 'Fitcheck', owner: 'Quốc Bảo', initials: 'QB', status: 'idea_pending', platforms: ['TikTok', 'Facebook'], due: 'Ngày mai', priority: '' },
  { id: 3, title: 'Biến hình cùng quần tây ống suông', type: 'Biến hình', owner: 'Hà My', initials: 'HM', status: 'idea_pending', platforms: ['TikTok', 'Shopee'], due: '12 Thg 6', priority: '' },
  { id: 4, title: 'Lookbook workwear — Chapter 01', type: 'Product detail', owner: 'Minh Anh', initials: 'MA', status: 'scripting', platforms: ['Instagram', 'Website'], due: '13 Thg 6', priority: 'Ưu tiên' },
  { id: 5, title: 'Từ văn phòng đến buổi hẹn', type: 'Tổng hợp outfit', owner: 'Huyền Trang', initials: 'HT', status: 'scripting', platforms: ['TikTok', 'Facebook'], due: '14 Thg 6', priority: '' },
  { id: 6, title: 'Áo sơ mi Oxford — 5 điểm khác biệt', type: 'Product detail', owner: 'Quốc Bảo', initials: 'QB', status: 'shooting_pending', platforms: ['TikTok', 'Shopee'], due: 'Hôm nay', priority: 'Gấp' },
  { id: 7, title: 'Weekend uniform: Navy edit', type: 'Lướt', owner: 'Hà My', initials: 'HM', status: 'shooting_pending', platforms: ['Instagram'], due: '15 Thg 6', priority: '' },
  { id: 8, title: '3 layer cho mùa mưa Sài Gòn', type: 'Biến hình', owner: 'Creator team', initials: 'CT', status: 'shooting_done', platforms: ['TikTok', 'Facebook'], due: 'Đã quay', priority: '' },
  { id: 9, title: 'Cargo pants — Street edit', type: 'Fitcheck', owner: 'Creator team', initials: 'CT', status: 'editing_done', platforms: ['TikTok', 'Instagram'], due: 'Chờ duyệt', priority: 'Review' },
  { id: 10, title: 'HAPPYORSAD essentials — 60s', type: 'Product detail', owner: 'Creator team', initials: 'CT', status: 'editing_done', platforms: ['TikTok', 'Shopee', 'Website'], due: 'Chờ duyệt', priority: '' },
  { id: 11, title: 'Summer tones — Reels cut', type: 'Tổng hợp outfit', owner: 'Creator team', initials: 'CT', status: 'published', platforms: ['Instagram', 'Facebook'], due: 'Đã đăng', priority: '' },
]

const platformStyles: Record<string, string> = { TikTok: 'bg-foreground text-background', Instagram: 'bg-pink-500/15 text-pink-600', Facebook: 'bg-blue-500/15 text-blue-600', Shopee: 'bg-orange-500/15 text-orange-600', Website: 'bg-muted text-muted-foreground' }

export default function Page() {
  const [role, setRole] = useState('lead')
  const [activeView, setActiveView] = useState('board')
  const [dark, setDark] = useState(true)
  const [search, setSearch] = useState('')
  const [cards, setCards] = useState(initialCards)
  const [showNew, setShowNew] = useState(false)

  const visibleCards = useMemo(() => cards.filter((card) => card.title.toLowerCase().includes(search.toLowerCase()) || card.type.toLowerCase().includes(search.toLowerCase())), [cards, search])
  const moveCard = (id: number, status: string) => setCards((items) => items.map((item) => item.id === id ? { ...item, status } : item))

  return (
    <div className={dark ? 'dark min-h-screen bg-background text-foreground' : 'min-h-screen bg-background text-foreground'}>
      <div className="flex min-h-screen">
        <aside className="hidden w-64 shrink-0 border-r border-border/70 bg-sidebar px-4 py-5 lg:flex lg:flex-col">
          <div className="mb-9 flex items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Clapperboard className="size-5" /></div><div><div className="font-semibold tracking-tight">HAPPYORSAD</div><div className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Media workspace</div></div></div>
          <div className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Workspace</div>
          <nav className="flex flex-col gap-1">
            <NavItem active={activeView === 'board'} icon={<Grid2X2 />} label="Content board" onClick={() => setActiveView('board')} />
            <NavItem active={activeView === 'inbox'} icon={<Inbox />} label="Inbox & duyệt" badge="7" onClick={() => setActiveView('inbox')} />
            <NavItem active={activeView === 'calendar'} icon={<CalendarDays />} label="Lịch đăng" onClick={() => setActiveView('calendar')} />
            <NavItem active={activeView === 'analytics'} icon={<BarChart3 />} label="Dashboard thống kê" onClick={() => setActiveView('analytics')} />
          </nav>
          <div className="mb-3 mt-9 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Library</div>
          <nav className="flex flex-col gap-1"><NavItem icon={<Archive />} label="Kho lưu trữ" /><NavItem icon={<FolderKanban />} label="Brand assets" /><NavItem icon={<Users />} label="Team" /></nav>
          <div className="mt-auto rounded-2xl border border-border/70 bg-card p-3"><div className="mb-2 flex items-center gap-2 text-xs font-medium"><Sparkles className="size-3.5 text-orange-400" /> AI Studio</div><p className="text-xs leading-relaxed text-muted-foreground">Tạo kịch bản, caption & hashtag nhanh hơn với Gemini.</p><button className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-medium text-primary-foreground" onClick={() => setShowNew(true)}>Mở AI Studio <ArrowUpRight className="size-3.5" /></button></div>
        </aside>
        <main className="min-w-0 flex-1">
          <header className="flex h-16 items-center justify-between border-b border-border/70 px-4 sm:px-7"><div className="flex items-center gap-3"><button className="lg:hidden"><Menu className="size-5" /></button><div className="lg:hidden"><div className="font-semibold">HAPPYORSAD</div></div><div className="hidden items-center gap-2 text-sm text-muted-foreground lg:flex"><span>Workspace</span><span>/</span><span className="text-foreground">Content board</span></div></div><div className="flex items-center gap-2"><button className="hidden rounded-lg border border-border/70 px-3 py-2 text-xs text-muted-foreground sm:flex sm:items-center sm:gap-2"><CircleHelp className="size-3.5" /> Help center</button><button onClick={() => setDark(!dark)} className="grid size-9 place-items-center rounded-lg border border-border/70 text-muted-foreground" aria-label="Đổi giao diện">{dark ? <Sun className="size-4" /> : <Moon className="size-4" />}</button><button className="relative grid size-9 place-items-center rounded-lg border border-border/70 text-muted-foreground"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-orange-400" /></button><div className="ml-1 flex items-center gap-2 border-l border-border/70 pl-3"><div className="grid size-8 place-items-center rounded-full bg-orange-400/20 text-xs font-semibold text-orange-500">LA</div><div className="hidden text-left sm:block"><div className="text-xs font-medium">Lan Anh</div><div className="text-[10px] text-muted-foreground">Lead</div></div><select value={role} onChange={(e) => setRole(e.target.value)} className="absolute right-4 top-14 z-10 w-28 cursor-pointer rounded-lg border border-border bg-card px-2 py-1 text-xs text-foreground opacity-0 hover:opacity-100 focus:opacity-100" aria-label="Chọn vai trò"><option value="lead">Lead</option><option value="content">Content</option><option value="creator">Creator</option></select></div></div></header>
          <div className="p-4 sm:p-7"><div className="mb-7 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-emerald-400" /> Thứ tư, 11 tháng 6, 2025</div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Xin chào, Lan Anh <span className="text-muted-foreground">—</span> <span className="text-muted-foreground">đây là workspace của bạn.</span></h1><p className="mt-2 text-sm text-muted-foreground">Theo dõi và đưa mọi nội dung về đích.</p></div><div className="flex flex-wrap items-center gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm kiếm nội dung..." className="h-9 w-52 rounded-lg border border-border/70 bg-card pl-9 pr-3 text-xs outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring" /></div><button className="flex h-9 items-center gap-2 rounded-lg border border-border/70 bg-card px-3 text-xs text-muted-foreground"><ListFilter className="size-3.5" /> Lọc</button><button onClick={() => setShowNew(true)} className="flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-xs font-medium text-primary-foreground"><Plus className="size-3.5" /> Tạo nội dung</button></div></div>
            <div className="mb-7 grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat icon={<Lightbulb />} label="Ý tưởng chờ duyệt" value="4" trend="+2 tuần này" /><Stat icon={<FileText />} label="Kịch bản đang viết" value="3" trend="68% hoàn thành" /><Stat icon={<Film />} label="Video chờ duyệt" value="2" trend="Cần xử lý" alert /><Stat icon={<Video />} label="Đã đăng tháng này" value="18" trend="+24% so với T5" /></div>
            {activeView === 'analytics' ? <Analytics /> : <><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-3"><h2 className="text-sm font-semibold">Production pipeline</h2><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">18 nội dung</span></div><button className="text-xs text-muted-foreground hover:text-foreground">Xem dạng danh sách <ArrowUpRight className="ml-1 inline size-3" /></button></div><div className="grid gap-3 overflow-x-auto pb-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{columns.map((column) => <section key={column.id} className="min-w-[270px]"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${column.color}`} /><h3 className="text-xs font-medium">{column.label}</h3><span className="text-xs text-muted-foreground">{visibleCards.filter((c) => c.status === column.id).length}</span></div><MoreHorizontal className="size-4 text-muted-foreground" /></div><div className="flex min-h-32 flex-col gap-2 rounded-xl bg-muted/40 p-2">{visibleCards.filter((c) => c.status === column.id).map((card) => <ContentCard key={card.id} card={card} role={role} onMove={moveCard} />)}{visibleCards.filter((c) => c.status === column.id).length === 0 && <div className="grid min-h-24 place-items-center text-center text-xs text-muted-foreground">Chưa có nội dung</div>}</div></section>)}</div></>}
          </div>
        </main>
      </div>
      {showNew && <NewContent onClose={() => setShowNew(false)} onCreate={(title) => { setCards((items) => [{ id: Date.now(), title, type: 'Ý tưởng mới', owner: 'Lan Anh', initials: 'LA', status: 'idea_pending', platforms: ['TikTok'], due: 'Mới tạo', priority: '' }, ...items]); setShowNew(false) }} />}
    </div>
  )
}

function NavItem({ icon, label, active, badge, onClick }: { icon: React.ReactNode; label: string; active?: boolean; badge?: string; onClick?: () => void }) { return <button onClick={onClick} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-xs transition ${active ? 'bg-accent text-foreground' : 'text-muted-foreground hover:bg-accent/60 hover:text-foreground'}`}>{icon}<span className="flex-1">{label}</span>{badge && <span className="rounded-md bg-orange-400/15 px-1.5 py-0.5 text-[10px] text-orange-500">{badge}</span>}</button> }
function Stat({ icon, label, value, trend, alert }: { icon: React.ReactNode; label: string; value: string; trend: string; alert?: boolean }) { return <div className="rounded-xl border border-border/70 bg-card p-4"><div className="mb-4 flex items-center justify-between"><span className="text-muted-foreground">{icon}</span>{alert && <span className="rounded-full bg-orange-400/15 px-2 py-1 text-[10px] text-orange-500">Review</span>}</div><div className="text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted-foreground">{label}</div><div className={`mt-3 text-[10px] ${alert ? 'text-orange-500' : 'text-emerald-500'}`}>{trend}</div></div> }
function ContentCard({ card, role, onMove }: { card: typeof initialCards[number]; role: string; onMove: (id: number, status: string) => void }) { return <article className="group rounded-lg border border-border/60 bg-card p-3 shadow-sm transition hover:border-orange-400/50"><div className="mb-3 flex items-start justify-between gap-2"><div className="flex flex-wrap gap-1">{card.platforms.map((platform) => <span key={platform} className={`rounded px-1.5 py-0.5 text-[9px] font-medium ${platformStyles[platform]}`}>{platform === 'Instagram' ? 'IG' : platform === 'Facebook' ? 'FB' : platform}</span>)}</div><button aria-label="Tùy chọn"><MoreHorizontal className="size-3.5 text-muted-foreground" /></button></div><h4 className="text-xs font-medium leading-relaxed">{card.title}</h4><div className="mt-2 text-[10px] text-muted-foreground">{card.type}</div><div className="mt-4 flex items-center justify-between border-t border-border/60 pt-3"><div className="flex items-center gap-2"><span className="grid size-5 place-items-center rounded-full bg-secondary text-[8px] font-semibold">{card.initials}</span><span className="max-w-20 truncate text-[10px] text-muted-foreground">{card.owner}</span></div><span className="text-[10px] text-muted-foreground">{card.due}</span></div>{role === 'lead' && card.status === 'idea_pending' && <div className="mt-3 flex gap-1.5"><button onClick={() => onMove(card.id, 'scripting')} className="flex flex-1 items-center justify-center gap-1 rounded-md bg-emerald-500/10 py-1.5 text-[10px] font-medium text-emerald-600"><Check className="size-3" /> Duyệt</button><button onClick={() => onMove(card.id, 'archived')} className="rounded-md bg-muted px-2 text-[10px] text-muted-foreground">Lưu</button></div>}{role === 'creator' && card.status === 'shooting_pending' && <button onClick={() => onMove(card.id, 'shooting_done')} className="mt-3 w-full rounded-md bg-primary py-1.5 text-[10px] font-medium text-primary-foreground">Đã quay xong</button>}{role === 'lead' && card.status === 'editing_done' && <button onClick={() => onMove(card.id, 'published')} className="mt-3 w-full rounded-md bg-primary py-1.5 text-[10px] font-medium text-primary-foreground">Duyệt video</button>}</article> }
function Analytics() { return <div className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-xl border border-border/70 bg-card p-5"><div className="mb-6 flex items-start justify-between"><div><h2 className="font-semibold">Năng suất team</h2><p className="mt-1 text-xs text-muted-foreground">Sản lượng nội dung trong 30 ngày qua</p></div><select className="rounded-lg border border-border/70 bg-background px-2 py-1.5 text-xs"><option>Tháng này</option><option>Tuần này</option></select></div><div className="flex h-52 items-end gap-3 border-b border-border/70 px-2">{[35, 52, 42, 70, 55, 80, 62, 92, 74, 65, 86, 98].map((height, i) => <div key={i} className="group flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-md bg-orange-400/70 transition group-hover:bg-orange-400" style={{ height: `${height}%` }} /><span className="text-[9px] text-muted-foreground">{i + 1}</span></div>)}</div></div><div className="rounded-xl border border-border/70 bg-card p-5"><div className="mb-6"><h2 className="font-semibold">Phân bổ nội dung</h2><p className="mt-1 text-xs text-muted-foreground">Theo format trong tháng này</p></div><div className="mx-auto mb-6 grid size-40 place-items-center rounded-full" style={{ background: 'conic-gradient(#fb923c 0 38%, #60a5fa 38% 64%, #a78bfa 64% 82%, #34d399 82% 100%)' }}><div className="grid size-24 place-items-center rounded-full bg-card"><span className="text-2xl font-semibold">18</span></div></div><div className="grid grid-cols-2 gap-3 text-xs"><Legend color="bg-orange-400" label="Fitcheck" value="38%" /><Legend color="bg-blue-400" label="Product detail" value="26%" /><Legend color="bg-violet-400" label="Biến hình" value="18%" /><Legend color="bg-emerald-400" label="Khác" value="18%" /></div></div></div> }
function Legend({ color, label, value }: { color: string; label: string; value: string }) { return <div className="flex items-center gap-2"><span className={`size-2 rounded-full ${color}`} /><span className="flex-1 text-muted-foreground">{label}</span><span>{value}</span></div> }
function NewContent({ onClose, onCreate }: { onClose: () => void; onCreate: (title: string) => void }) { const [title, setTitle] = useState(''); return <div className="fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><div className="mb-1 flex items-center gap-2 text-orange-500"><WandSparkles className="size-4" /> Quick create</div><h2 className="text-lg font-semibold">Tạo ý tưởng mới</h2><p className="mt-1 text-xs text-muted-foreground">Bắt đầu một nội dung cho HAPPYORSAD.</p></div><button onClick={onClose}><X className="size-4 text-muted-foreground" /></button></div><label className="text-xs font-medium">Tên ý tưởng<textarea autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder="VD: 3 cách phối đồ đi làm..." className="mt-2 h-24 w-full resize-none rounded-lg border border-border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label><div className="mt-4 flex items-center justify-between rounded-lg bg-orange-400/10 p-3 text-xs text-orange-600"><Sparkles className="size-4" /><span className="flex-1 px-2">AI có thể gợi ý shotlist & caption sau khi tạo</span></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg px-4 py-2 text-xs text-muted-foreground">Hủy</button><button disabled={!title.trim()} onClick={() => onCreate(title)} className="rounded-lg bg-primary px-4 py-2 text-xs font-medium text-primary-foreground disabled:opacity-40">Tạo ý tưởng</button></div></div></div> }
